package de.enwida.transport;

public enum Aspect {
	
	VOL_ACTIVATION,
	DEGREE_OF_ACTIVATION,
	VOL_ACCEPTED,
	VOL_OFFERED,
	POWERPRICE_ACCEPTED,
	POWERPRICE_REJECTED,
	WORKPRICE_ACCEPTED,
	WORKPRICE_REJECRED,
	POWERPRICE_MIN,
	POWERPRICE_MID,
	POWERPRICE_MAX,
	WORKPRICE_ACC_MIN,
	WORKPRICE_ACC_MID,
	WORKPRICE_ACC_MAX,
	WORKPRICE_MARG_MID,
	WORKPRICE_MARG_MAX

}
