// Generated by CoffeeScript 1.6.2
(function() {
  require.config({
    baseUrl: "/enwida/resources/js/chart/lib"
  });

  require(["chart_manager", "navigation"], function(ChartManager, Navigation) {
    return $(document).ready(function() {
      return $(".chart").each(function() {
        var id;

        id = $(this).attr("data-chart-id");
        return ChartManager.attachTo($(this), {
          id: id
        });
      });
    });
  });

}).call(this);
