// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    baseUrl: "/enwida/resources/js/chart/lib"
  });

  require(["util/logger", "components/chart_manager"], function(Logger, ChartManager) {
    return $(document).ready(function() {
      window.Logger = Logger.init("debug");
      return $(".chart").each(function() {
        var id;
        id = $(this).attr("data-chart-id");
        return ChartManager.attachTo($(this), {
          id: id
        });
      });
    });
  });

}).call(this);
