// Generated by CoffeeScript 1.6.2
(function() {
  require.config({
    baseUrl: "/enwida/resources/js/chart/lib"
  });

  require(["line_chart", "bar_chart", "carpet_chart"], function(LineChart, BarChart, CarpetChart) {
    var drawData, drawUrl, exampleUrl;

    exampleUrl = "json?type=rl_ab1&product=210&startTime=2010-12-30&endTime=2010-12-31&resolution=HOURLY";
    drawData = function(data) {
      var lineChart;

      $("#chart svg").remove();
      console.log(JSON.stringify(data));
      console.log(d3.legend);
      $("#chart h3").text(data.metaData.chartTitle);
      $("#legend").text(data.allDataLines.map(function(dl) {
        return dl.yTitle;
      }));
      lineChart = LineChart.init({
        parent: "#chart",
        data: data,
        scale: {
          x: {
            type: "date"
          }
        }
      });
      return lineChart.draw();
    };
    drawUrl = function(url) {
      return $.ajax(url, {
        success: drawData,
        error: function(err) {
          return alert(err);
        }
      });
    };
    return $(document).ready(function() {
      $("#url").keyup(function(e) {
        if (e.which !== 13) {
          return;
        }
        return drawUrl($("#url").val());
      });
      $("#templates a").click(function(e) {
        $("#url").val($(e.target).text());
        return drawUrl($(e.target).text());
      });
      $("#url").val(exampleUrl);
      return drawUrl(exampleUrl);
    });
  });

}).call(this);
