// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    baseUrl: "/enwida/resources/js/chart/lib"
  });

  require(["util/logger", "components/download_manager"], function(Logger, DownloadManager) {
    return $(document).ready(function() {
      var id;
      window.Logger = Logger.init("debug");
      id = parseInt(window.location.search.replace("?chartId=", ""));
      return DownloadManager.attachTo($(".download"), {
        id: id
      });
    });
  });

}).call(this);
